# Default values for egress-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
citrixCPX: false

coe:
    coeURL:
    coeTracing: false

metricExporter:
    required: true
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.8
    port: 8888
    secure: "FALSE"
    logLevel: ERROR
    imagePullPolicy: IfNotPresent

istioPilot:
    name: istiod
    namespace: istio-system
    secureGrpcPort: 15012
    insecureGrpcPort: 15010
    SAN:


xDSAdaptor:
    image: quay.io/citrix/citrix-xds-adaptor:0.9.8
    imagePullPolicy: IfNotPresent
    proxyType: router
    secureConnect: true
    logLevel: DEBUG
    jsonLog: false


certProvider:
    caAddr: istiod.istio-system.svc
    caPort: 15012
    trustDomain: cluster.local
    certTTLinHours: 720
    clusterId: Kubernetes
    jwtPolicy: first-party-jwt #specify third-party-jwt if Kubernetes cluster supports third-party tokens


egressGateway:
    netscalerUrl: null
    image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-79.64
    imagePullPolicy: IfNotPresent
    EULA: false
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    lightWeightCPX: "1"    
    label: citrix-egressgateway
    vserverIP: nsip
    adcServerName:
    netProfile:

ADMSettings:
    ADMIP:
    licenseServerIP:
    licenseServerPort: 27000
    bandWidthLicense: false
    bandWidth:
    vCPULicense: false
    cpxCores:

secretName: nsloginegress
